# These are supported funding model platforms

github: [AnkanSaha]
# patreon:
# open_collective: banglacode
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# lfx_crowdfunding:
# polar:
