name: Feature Request
description: Suggest a new feature for BanglaCode
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input in making BanglaCode better.

        Please search existing issues first to avoid duplicates.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Language Feature (new keyword, syntax)
        - Built-in Function
        - Standard Library
        - Performance
        - Error Messages
        - REPL Enhancement
        - VSCode Extension
        - Documentation
        - Tooling (formatter, linter)
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm frustrated when...
        It would be easier if...
        Currently, I have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: |
        I would like to have...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: syntax
    attributes:
      label: Proposed Syntax (if applicable)
      description: If this is a language feature, show how it would look.
      render: banglacode
      placeholder: |
        // Example of how the new feature would be used
        dhoro result = newFeature(arg);
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered.
      placeholder: |
        Other ways this could be done...
        Workarounds I currently use...
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature.
      placeholder: |
        1. When building a web application...
        2. When working with data...
        3. For educational purposes...
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this feature require breaking existing code?
      options:
        - "No - fully backwards compatible"
        - "Maybe - some edge cases might break"
        - "Yes - requires migration"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I can implement this"
        - "Yes, I can help with guidance"
        - "No, but I can test it"
        - "No"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have considered the impact on existing code
          required: true
